config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#index'

  get '/:url', to: 'pages#show', as: :page
  patch '/:url', to: 'pages#update', as: :update_page

  scope module: :page do
    get '/:url/file', to: 'files#show', as: :page_file
    post '/:url/file', to: 'files#create_or_update', as: :create_page_file
    patch '/:url/file', to: 'files#create_or_update', as: :update_page_file
    delete '/:url/file', to: 'files#delete', as: :delete_page_file
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
# frozen_string_literal: true

class Page < ApplicationRecord
  validates :url, presence: true, uniqueness: true
  has_one_attached :file

  MAX_FILE_SIZE = 100.0.megabytes

  validate :file_size

  private

  def file_size
    return unless file.attached? && file.byte_size > MAX_FILE_SIZE

    self.file = nil
    errors.add(:file, 'File is too big. Max size is 100mb.')
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception, unless: -> { request.format.json? }

  private

  def set_page
    @page = Page.find_or_create_by(url_param)
  end

  def url_param
    params.permit(:url)
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render(status: 404)
  end

  def internal_server_error
    render(status: 500)    
  end
end

app/controllers/page/files_controller.rb
# frozen_string_literal: true

class Page::FilesController < ApplicationController
  before_action :set_page

  def show
    respond_to do |format|
    end
  end

  def create_or_update
    respond_to do |format|
      if @page.update(file_param)
        format.any(:html, :json) { render 'pages/show' }
      else
        format.html { render 'pages/show', status: :not_acceptable }
        format.json { render json: @page.errors, status: :not_acceptable }
      end
    end
  end

  def delete
    @page.file.purge

    respond_to do |format|
      format.html { redirect_back(fallback_location: 'show') }
      format.json { render 'pages/show' }
    end
  end

  private

  def set_page
    @page = Page.find_or_create_by(url_param)
  end

  def file_param
    params.require(:page).permit(:file)
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  before_action :set_page

  def index; end

  def show
    respond_to do |format|
      format.zip { download_zip_file }
      format.any(:html, :json) { render 'show' }
    end
  end

  def update
    respond_to do |format|
      if @page.update(update_page_params)
        format.any(:html, :json) { render 'show' }
      else
        format.html { render 'show', status: :not_acceptable }
        format.json { render json: @page.errors, status: :not_acceptable }
      end
    end
  end

  private

  def update_page_params
    params.require(:page).permit(:content, :url, :file)
  end

  def download_zip_file
    zip_filename = "tmp/#{@page.url}.zip"

    Zip::File.open(zip_filename, Zip::File::CREATE) do |zipfile|
      zipfile.get_output_stream("#{@page.url}.txt") { |f| f.write @page.content }

      if @page.file.attached?
        filepath = ActiveStorage::Blob.service.path_for @page.file.key
        zipfile.add(@page.file.filename.to_s, filepath)
      end
    end

    send_file zip_filename
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def title(page_title)
    content_for(:title) { page_title }
  end
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
  def attachment_icon(content_type)
    icon_classes = case content_type
                   when %r{/pdf} then { style: 'far', name: 'file-pdf' }
                   when %r{image/} then { style: 'far', name: 'file-image' }
                   when %r{/zip} then { style: 'far', name: 'file-archive' }
                   when %r{video/} then { style: 'far', name: 'file-video' }
                   else
                     { style: 'far', name: 'file-alt' }
                   end

    icon(icon_classes[:style], icon_classes[:name])
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dontfile<%= content_for?(:title) ? ' | ' + yield(:title) : ''%></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css" integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/errors.html.erb
<h1>Dontfile</h1> 
<div class="wrap">
    <div class="body">
        <h2>Page Not Found</h2>
        <p>Sorry, but the page you were trying to view does not exist.</p>
    </div>
</div>

app/views/pages/index.html.erb
<div class="welcome-container">
  <h1 class="welcome-title">Dontfile</h1>
  <p class="welcome-description">The dontpad of files</p>
</div>
<form class="welcome-router" action="javascript:goToPage()">
  <span>www.dontfile.com/</span>
  <input type="text" id="input"></input>
  <button>Go!</button>
</form>

<div class="welcome-container">
  <div class="welcome-sub-description">
    Don't sign in, just use a URL<br>
    Don't save, text is saved automatically<br>
    Don't send files, just share your URL<br>
    Don't lose your content, download with YourURL.zip<br>
    Dontfile!
  </div>
</div>
<div class="welcome-container welcome-footer">
  <%= icon('fab', 'github') %>
  <span>Join us on</span>
  <a href="https://github.com/dontfile/dontfile" target="_blank">Github!</a>  
</div>

app/views/pages/show.html.erb
<% title @page.url %>

<h1>Dontfile</h1>

<div id="container" data-path="<%= @page.url %>">
  <div id="text-area">
    <h2>Text</h2>
    <textarea id="text"><%= @page.content %></textarea>
  </div>

  <h2>File</h2>
  <div id="file-area">
    <div>
      <h4>(Max size: 100mb)</h4>
      <input type="file" id="file" onchange="saveFile()">
    </div>

    <div id="attachment">
      <% if @page.file.attached? %>
        <%= attachment_icon(@page.file_blob.content_type) %>
        <p><%= @page.file_blob.filename %></p>

        <div id="buttons">
          <a class="button" title='Download File' href="<%= rails_blob_url(@page.file) %>" download>
            <%= icon('far', 'arrow-alt-circle-down') %>
          </a>

          <%= button_to delete_page_file_path,
                        method: :delete,
                        params: { url: @page.url },
                        title: 'Delete File',
                        data: { confirm: "Are you sure?" },
                        class: 'button' do %>
            <%= icon('far', 'trash-alt') %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <progress id="file-upload-progress" value="0"></progress>
</div>

app/views/welcome/index.html.erb
<div class="welcome-container">
    <h1 class="welcome-title">Dontfile</h1>
    <p class="welcome-description">The dontpad of files</p>
</div>
<div class="welcome-router">
    www.dontfile.com/&nbsp&nbsp&nbsp&nbsp<input type="text" name="input_url"></input>
</div>

<div class="welcome-container">
    <div class="welcome-sub-description">
        Dont sign in, just use a URL<br>
        Dont save, text is saved automatically<br>
        Dont save x2, just upload your file<br>
        Dontfile!
    </div>
</div>